Change optionalModules to modules as checkout location
LabKey/wnprc-modules pull request #10
Opened 2020-05-11 19:01 UTC by labkey-ians

#### Rationale
Consolidate to server/modules as the preferred location for building module code 

#### Related Pull Requests
https://github.com/LabKey/platform/pull/1155

#### Changes
Update build.gradle

2020-05-11 20:10 UTC, labkey-tchad approved these changes

2020-05-11 20:11 UTC, labkey-tchad requested changes
Should we add a `gradle.properties` file with `moduleContainer=:server:modules:wnprc-modules`?

2020-05-11 20:16 UTC, labkey-susanh commented
> Should we add a `gradle.properties` file with `moduleContainer=:server:modules:wnprc-modules`?

Since we have the special check for this repository in `server/modules/build.gradle`, it's not strictly necessary now.  Could be done now to save having to remember later, though.

2020-05-11 22:26 UTC, labkey-tchad approved these changes

2020-05-13 13:27 UTC, labkey-susanh approved these changes

2020-05-13 15:06 UTC, merged