Remove unused reference to Commons Net
LabKey/wnprc-modules pull request #545
Opened 2024-03-20 20:27 UTC by labkey-adam

#### Rationale
No longer needed

2024-03-20 22:35 UTC, labkey-jeckels approved these changes

2024-03-20 22:37 UTC, labkey-jeckels requested changes
https://teamcity.labkey.org/buildConfiguration/LabKey_Trunk_Premium_VerifyJavaBuild/2957508?expandBuildDeploymentsSection=false&hideTestsFromDependencies=false&hideProblemsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true

Likely an accidental import of the wrong TimeStamp

2024-03-21 05:18 UTC, labkey-adam commented
> https://teamcity.labkey.org/buildConfiguration/LabKey_Trunk_Premium_VerifyJavaBuild/2957508?expandBuildDeploymentsSection=false&hideTestsFromDependencies=false&hideProblemsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true
> 
> Likely an accidental import of the wrong TimeStamp

Yep: https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=49739

Just needed to merge the fix into this PR

2024-03-21 16:16 UTC, labkey-jeckels approved these changes

2024-03-21 20:44 UTC, merged